Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/09/2022
Var
v: vetor[0..3] de inteiro
votos, i, j, cont1, cont2: inteiro

Inicio
repita
escreval("digite 12 para Ciro Gomes, digite 15 para Simone Tebet")
leia(v[i])
i < - i + 1
votos < - votos + 1
limpatela
ate votos = 4
escreval ("fim da eleição")
para j de 0 ate 3 faca
cont1 < - cont1+1
fimse
se v9[J] = 22 entao
cont2 < - cont2 + 1
fimse
fimpara
escreval ("votos para 12:", cont1)
escreval ("votos para 15:", cont2)
Fimalgoritmo